### ISSUE TITLE
No option to upload images

### ISSUE THREAD

**Issue by stevecrossuk** [seandowney/laravel-backpack-gallery-crud#5]
I have no ability to upload images - looking at the code it only says to show the table with the ability to order gallery items if there are photos already in the row in the database.

**Comment by straybro** [comment]
The basic idea was to upload images via elfinder

**Comment by mjpramos** [comment]
I solved it by creating a new folder in the File Manager (backoffice) with the same name as the gallery slug.
Uploaded some photos and the thumbnails were generated. Another bug was that, after uploading, I edited the gallery and all the images where not loading. Turns out I uploaded all jpg's and in the 
resources/views/vendor/seandowney/gallerycrud/gallery.blade.php file, line 26, png was hardcoded, so they ended up like aaa.jpg.png.

**Comment by seandowney** [comment]
@mjpramos thanks for that I will change it now
